### ISSUE TITLE
Web version shows white box instead of UI

### ISSUE THREAD

**Issue by theomgdev** [SuperSpaceEye/LifeEngineExtended#47]
![wb](https://user-images.githubusercontent.com/29312699/195600476-f4c9e3f4-2578-421b-ae37-44d4fcefc797.png)

I have tried with Brave Browser, Chromium, and Opera but the situation is the same. I can't see but I can interact with textboxes, buttons, etc. My system is Ubuntu LTS 20.04. But everything works fine in my mobile phone's browser.

I have tried figuring it out but I don't know how WebAssembly works.

Thanks for everything, I am a big fan of LifeEngine and you are my hero because the performance of LifeEngineExtended is mesmerizing with a lot of features if I consider my PC sucks :)

**Comment by SuperSpaceEye** [comment]
I don't really know how web assembly works either, but without error message I can't really help much.

**Comment by theomgdev** [comment]
![solution_is_mobile_mode](https://user-images.githubusercontent.com/29312699/195707347-c66fc218-cb36-470f-b064-0459d58abe95.png)

I think I have found a temporary solution.

I open the developer console by pressing CTRL+SHIFT+I on the loading screen. (Because of WebAssembly handles the action of the CTRL and SHIFT keys after the loading screen.)

Then I activate the mobile device mode from the top right button and everything works like magic. (Maybe hard-refreshing using CTRL+F5 on the page after that is a good idea if It doesn't work. Also, I am usually scaling device width from the top bar of developer settings to see controls more clearly.)

**Comment by SuperSpaceEye** [comment]
It's good that you have managed to figure out workaround, because I can't reproduce your problem. Btw you can set font size and menu height in settings.
